Resources:
  SMSCryptoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      # Generate a name based on the stage
      TableName: ${self:custom.tableName}
      AttributeDefinitions:
        - AttributeName: cryptoSymbol
          AttributeType: S
        - AttributeName: cryptoDate
          AttributeType: S
      KeySchema:
        - AttributeName: cryptoSymbol
          KeyType: HASH
        - AttributeName: cryptoDate
          KeyType: RANGE
      # Set the capacity based on the stage
      ProvisionedThroughput:
        ReadCapacityUnits: ${self:custom.tableThroughput}
        WriteCapacityUnits: ${self:custom.tableThroughput}